# General
name: Nikson69
description: "Live, unix, development etc"
url: http://nikson69.github.io
#url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: Nikson69s
twitter: Nikson69ru
github: yourusername
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"