# General
name: Nikson69
description: "Live, unix, development etc"
#url: http://nikson69.github.io
url: http://localhost:4000

markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
#markdown: kramdown
#highlighter: pygments

gems: [jekyll-paginate]

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: Nikson69
twitter: Nikson69ru
github: yourusername
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
