# General
name: Nikson69
description: "Live, unix, development etc"
url: http://nikson69.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: yourusername
github: yourusername
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
